SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;


SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME ,EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;