SELECT  m.FIRST_NAME, e.MANAGER_ID
FROM EMPLOYEES AS e
	JOIN EMPLOYEES AS m
    ON e.EMPLOYEE_ID = m.MANAGER_ID;
    
    
------------------------

CREATE DATABASE MIDTERM;
USE MIDTERM;

CREATE TABLE Employees(
Employee_Id INT PRIMARY KEY,
First_Name VARCHAR(50) NOT NULL,
Last_Name VARCHAR(50) NOT NULL,
Date_of_Birth date NOT NULL,
Department_Id INT ,
Salary INT 
);

CREATE TABLE Projects(
Project_ID INT PRIMARY KEY,
Project_Name VARCHAR(50) UNIQUE,
Start_Date DATE,
End_Date DATE,
Budget INT
);


SELECT EMPLOYEES.EMPLOYEE_ID, PROJECTS.PROJECT_ID
FROM EMPLOYEES 
	CROSS JOIN PROJECTS;
----------------------------
USE DUMMYDB;

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (
	SELECT MAX(SALARY)
	FROM EMPLOYEES
	WHERE SALARY < (
		SELECT MAX(SALARY)
		FROM EMPLOYEES)
);
------------------------------

SELECT DEPARTMENT_NAME, COUNT(EMPLOYEES.EMPLOYEE_ID) AS Number_of_Employees
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    GROUP BY DEPARTMENTS.DEPARTMENT_NAME;
-------------------

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
CROSS JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

---------------------------------

WITH EMP_SAL AS(
SELECT AVG(SALARY) SAL
FROM EMPLOYEES
)
SELECT CONCAT(FIRST_NAME, ' ',  LAST_NAME) AS FULL_NAME
FROM EMPLOYEES
WHERE SALARY > (SELECT SAL FROM EMP_SAL);

------------------------

SELECT CONCAT(FIRST_NAME, ' ',  LAST_NAME) AS FULL_NAME
FROM EMPLOYEES
WHERE SALARY <
(SELECT SALARY
FROM EMPLOYEES
WHERE FIRST_NAME = 'STEVEN' && LAST_NAME = 'KING');
-----------------

SELECT DEPARTMENT_NAME, CONCAT(EMPLOYEES.FIRST_NAME, ' ',  EMPLOYEES.LAST_NAME) AS MANAGER_NAME
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES ON DEPARTMENTS.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID;
    
--------------------

SELECT DISTINCT CITY
FROM LOCATIONS
 INNER JOIN DEPARTMENTS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;















    
 










